-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, sum(TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF as fh
INNER JOIN ICECREAM_INFO as ii
on fh.FLAVOR = ii.FLAVOR
group by ii.INGREDIENT_TYPE 
order by sum(TOTAL_ORDER)